### ISSUE TITLE
CLI action breaking after Octocat changes

### ISSUE THREAD

**Issue by GeeWee** [fastly/compute-actions#18]
Hello. After running the setup action successfully for a while, it's started failing with the following error

```
Run fastly/compute-actions/setup@v2
(node:2829) UnhandledPromiseRejectionWarning: Error: [@octokit/auth-action] `GITHUB_TOKEN` variable is not set. It must be set on either `env:` or `with:`. See https://github.com/octokit/auth-action.js#createactionauth
    at createActionAuth (/home/runner/work/_actions/fastly/compute-actions/v2/node_modules/@octokit/auth-action/dist-node/index.js:15:11)
    at new Octokit (/home/runner/work/_actions/fastly/compute-actions/v2/node_modules/@octokit/core/dist-node/index.js:111:20)
    at new _a (/home/runner/work/_actions/fastly/compute-actions/v2/node_modules/@octokit/core/dist-node/index.js:165:30)
    at new OctokitWithDefaults (/home/runner/work/_actions/fastly/compute-actions/v2/node_modules/@octokit/core/dist-node/index.js:145:9)
    at downloadCLI (/home/runner/work/_actions/fastly/compute-actions/v2/setup/index.js:44:16)
    at setup (/home/runner/work/_actions/fastly/compute-actions/v2/setup/index.js:14:11)
(node:2829) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2829) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My task looks like this:
```yaml
      - name: Set up Fastly CLI
        uses: fastly/compute-actions/setup@main
```

(I have also tried with `@v2` instead of `@main` and get the same error)

I would imagine this is related to [this commit](https://github.com/fastly/compute-actions/commit/4b62867a9e60044bd55f3037a0fe5e11973316b9)

**Comment by agouil** [comment]
Found this in the auth-action [readme](https://github.com/octokit/auth-action.js#createactionauth):
```
It expects the GITHUB_TOKEN variable to be set which is provided to GitHub Actions, but [has to be configured explicitly](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token).
```

It's fixed by added `token` to the step definition like,
```
- name: Set up Fastly CLI
   uses: fastly/compute-actions/setup@main
   with:
     token: ${{ secrets.GITHUB_TOKEN }}
     cli_version: '1.7.1'
```
... but throws a warning `Warning: Unexpected input(s) 'token', valid inputs are ['cli_version']`

**Comment by GeeWee** [comment]
Can confirm that this is solved on @main, but @v2 still has the issue as it hasn't been updated with the latest commits.
